module.exports={
    User:require('./User'),
    Product:require('./Product'),
    Review:require('./Review'),
    Reply:require('./Reply'),
    Recommend:require('./Recommend'),
    Chat:require('./Chat'),
    ReviewRating:require('./ReviewRating'),
    ProductRating:require('./ProductRating')
}